# Perkenalan

In [29]:
'''
=================================================
Milestone 3

Nama  : Rolando Krisnanto
Batch : CODA-RMT-021

Program ini dibuat untuk melakukan Expolatory Data Analysis sederhana dan melakukan Validasi Data menggunakan Library Great Expectation.
=================================================
'''

'\n=================================================\nMilestone 3\n\nNama  : Rolando Krisnanto\nBatch : CODA-RMT-021\n\nProgram ini dibuat untuk melakukan Expolatory Data Analysis sederhana dan melakukan Validasi Data menggunakan Library Great Expectation.\n=================================================\n'

# Inisialisasi

In [30]:
# Install Great Expectations
!pip install great_expectations

Requirement already satisfied: great_expectations in c:\users\rolan\anaconda3\lib\site-packages (1.23.0)
Requirement already satisfied: altair<7.0.0,>=5.0.0 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (5.5.0)
Requirement already satisfied: cryptography>=3.2 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (46.0.3)
Requirement already satisfied: jinja2>=3 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (3.1.6)
Requirement already satisfied: jsonschema>=2.5.1 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (4.25.0)
Requirement already satisfied: marshmallow>=3.18.0 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (4.3.1)
Requirement already satisfied: mistune>=0.8.4 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (3.1.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (2.3.5)
Requirement already satisfied: packaging in c:\users\rolan\appdata\roaming\python\python313\site-packages (from great_expectations) (26.2)
Requirement already satisfied: pandas>=1.3.0 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (2.3.3)
Requirement already satisfied: pydantic>=1.10.7 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (2.12.4)
Requirement already satisfied: pyparsing!=3.2.4,>=2.4 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (3.2.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\rolan\appdata\roaming\python\python313\site-packages (from great_expectations) (2.9.0.post0)
Requirement already satisfied: requests>=2.20 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (2.32.5)
Requirement already satisfied: ruamel.yaml>=0.16 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (0.18.16)
Requirement already satisfied: scipy>=1.6.0 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (1.16.3)
Requirement already satisfied: tqdm>=4.59.0 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (4.67.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\rolan\appdata\roaming\python\python313\site-packages (from great_expectations) (4.16.0)
Requirement already satisfied: tzlocal>=1.2 in c:\users\rolan\anaconda3\lib\site-packages (from great_expectations) (5.4.4)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\rolan\anaconda3\lib\site-packages (from altair<7.0.0,>=5.0.0->great_expectations) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\rolan\anaconda3\lib\site-packages (from cryptography>=3.2->great_expectations) (2.0.0)
Requirement already satisfied: pycparser in c:\users\rolan\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=3.2->great_expectations) (2.23)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rolan\anaconda3\lib\site-packages (from jinja2>=3->great_expectations) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\rolan\anaconda3\lib\site-packages (from jsonschema>=2.5.1->great_expectations) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\rolan\anaconda3\lib\site-packages (from jsonschema>=2.5.1->great_expectations) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\rolan\anaconda3\lib\site-packages (from jsonschema>=2.5.1->great_expectations) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\rolan\anaconda3\lib\site-packages (from jsonschema>=2.5.1->great_expectations) (0.28.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rolan\anaconda3\lib\site-packages (from pandas>=1.3.0->great_expectations) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rolan\anaconda3\lib\site-packages (from pandas>=1.3.0->great_expectations) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\rolan\anaconda3\lib\site-packages (from pydantic>=1.10.7->great_expectations) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\rolan\anaconda3\lib\site-packages (from pydantic>=1.10.7->great_expectations) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\rolan\anaconda3\lib\site-packages (from pydantic>=1.10.7->great_expectations) (0.4.2)
Requirement already satisfied: six>=1.5 in c:\users\rolan\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.1->great_expectations) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\rolan\anaconda3\lib\site-packages (from requests>=2.20->great_expectations) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rolan\anaconda3\lib\site-packages (from requests>=2.20->great_expectations) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rolan\anaconda3\lib\site-packages (from requests>=2.20->great_expectations) (2.7.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rolan\anaconda3\lib\site-packages (from requests>=2.20->great_expectations) (2026.7.22)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in c:\users\rolan\anaconda3\lib\site-packages (from ruamel.yaml>=0.16->great_expectations) (0.2.14)
Requirement already satisfied: colorama in c:\users\rolan\appdata\roaming\python\python313\site-packages (from tqdm>=4.59.0->great_expectations) (0.4.6)

In [31]:
# Inisialisasi EDA & Great Expectation
import great_expectations as gx
import pandas as pd

# Exploratory Data Analysis

Melakukan pengecekan, cleaning, dan perbaikan data sederhana sebelum masuk ke tahap Cek Validasi menggunakan Great Expectation

In [32]:
# Read CSV File dan menampilkan 5 data teratas
df = pd.read_csv('data/P2M3_rolando_krisnanto_data_raw.csv')

df.head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [33]:
# Cek Sturuktur Data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  object
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), object(9)
memory usage: 15.5+ MB

In [34]:
# Cek Data Duplikat
cek_dupl = df.duplicated().sum()

print ("Jumlah Data Duplikat : ", cek_dupl)

Jumlah Data Duplikat :  1000

In [35]:
# Ubah Tipe Data Kolom 'Date' menjadi Datetime
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')

df.info()

df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  datetime64[ns]
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: datetime64[ns](1), int64(9), object(8)
memory usage: 15.5+ MB

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [36]:
# Hapus row yang duplikat
df = df.drop_duplicates()

# Reset index agar urutan index mulai dari 0 lagi
df = df.reset_index(drop=True)

# Cek jumlah baris setelah drop data duplikat & cek data duplikat yang tersisa
print("Jumlah baris setelah hapus data duplikat:", len(df))
print("Jumlah data duplikat:", df.duplicated().sum())

df.head(5)

Jumlah baris setelah hapus data duplikat: 112036
Jumlah data duplikat: 0

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [37]:
# Buat Kolom Identifier untuk setiap baris yang diwakili oleh Transaction ID
df['Transaction_ID'] = range(1, len(df) + 1)

# Pindahkan Kolom Transaction_ID ke posisi paling kiri
## Ambil kolomnya dulu dan hapus dari dataframe
transaction_id = df.pop('Transaction_ID')

## masukkan lagi ke dataframe di posisi index ke-0
df.insert(0, 'Transaction_ID', transaction_id)

df.head(5)

,Transaction_ID,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,1,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,3,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,4,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,5,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

# Great Expectation

Validasi data dengan library Great Expectation

In [38]:
# Buat Data Context untuk Great Expectation
context = gx.get_context()

In [39]:
# Membuat Data Source untuk pandas
data_source = context.data_sources.add_pandas("europe-bike-sales-source")

# Membuat Data Asset dari dataframe pandas
data_asset = data_source.add_dataframe_asset(name="europe-bike-sales-asset")

# Membuat Batch Definition (seluruh dataframe) untuk data asset
batch_definition = data_asset.add_batch_definition_whole_dataframe("bike-sales-batch")

# Ambil Batch, masukkan data frame yang sudah melalui EDA dan Cleaning
batch = batch_definition.get_batch(batch_parameters={"dataframe": df})

In [40]:
# Expectation 1 - To Be Unique
## untuk memvalidasi kolom Transaction_ID agar tidak ada duplikat
expectation = gx.expectations.ExpectColumnValuesToBeUnique(
    column="Transaction_ID"
)
result = batch.validate(expectation)
result

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

{
  "success": true,
  "expectation_config": {
    "type": "expect_column_values_to_be_unique",
    "kwargs": {
      "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
      "column": "Transaction_ID"
    },
    "meta": {},
    "severity": "critical"
  },
  "result": {
    "element_count": 112036,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0,
    "partial_unexpected_counts": [],
    "partial_unexpected_index_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [41]:
# Expectation 2 - To Be Between (Min Value and Max Value)
## untuk memvalidasi kolom Customer_Age agar nilainya harus di antara 0 dan 90
expectation = gx.expectations.ExpectColumnValuesToBeBetween(
    column="Customer_Age", 
    min_value=0, 
    max_value=90
)
result = batch.validate(expectation)
result

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

{
  "success": true,
  "expectation_config": {
    "type": "expect_column_values_to_be_between",
    "kwargs": {
      "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
      "column": "Customer_Age",
      "min_value": 0.0,
      "max_value": 90.0
    },
    "meta": {},
    "severity": "critical"
  },
  "result": {
    "element_count": 112036,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0,
    "partial_unexpected_counts": [],
    "partial_unexpected_index_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [42]:
# Expectation 3 - To Be In Set
## untuk memvalidasi kolom Customer_Gender agar nilainya harus "M" atau "F"
expectation = gx.expectations.ExpectColumnValuesToBeInSet(
    column="Customer_Gender", 
    value_set=["M", "F"]
)
result = batch.validate(expectation)
result

Calculating Metrics:   0%|          | 0/10 [00:00<?, ?it/s]

{
  "success": true,
  "expectation_config": {
    "type": "expect_column_values_to_be_in_set",
    "kwargs": {
      "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
      "column": "Customer_Gender",
      "value_set": [
        "M",
        "F"
      ]
    },
    "meta": {},
    "severity": "critical"
  },
  "result": {
    "element_count": 112036,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0,
    "partial_unexpected_counts": [],
    "partial_unexpected_index_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [43]:
# Expectation 4 - To Be In Type List
## untuk memvalidasi kolom Date tipe datanya harus sesuai yang ditentukan, yaitu datetime64[ns]
expectation = gx.expectations.ExpectColumnValuesToBeInTypeList(
    column="Date", 
    type_list=["datetime64[ns]"]
)
result = batch.validate(expectation)
result

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "expectation_config": {
    "type": "expect_column_values_to_be_in_type_list",
    "kwargs": {
      "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
      "column": "Date",
      "type_list": [
        "datetime64[ns]"
      ]
    },
    "meta": {},
    "severity": "critical"
  },
  "result": {
    "observed_value": "datetime64"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [44]:
# Expectation 5 - Column Pair Values A to Be Greater Than B 
## untuk memvalidasi kolom Unit_Price datanya harus lebih besar dari kolom Unit_Cost
expectation = gx.expectations.ExpectColumnPairValuesAToBeGreaterThanB(
    column_A="Unit_Price", 
    column_B="Unit_Cost",
    or_equal=True
)
result = batch.validate(expectation)
result

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

{
  "success": true,
  "expectation_config": {
    "type": "expect_column_pair_values_a_to_be_greater_than_b",
    "kwargs": {
      "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
      "column_A": "Unit_Price",
      "column_B": "Unit_Cost",
      "or_equal": true
    },
    "meta": {},
    "severity": "critical"
  },
  "result": {
    "element_count": 112036,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0,
    "partial_unexpected_counts": [],
    "partial_unexpected_index_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [45]:
# Expectation 6 - Value Lengths To Be Between
## untuk memvalidasi panjang nilai di kolom Product harus di antara 5 dan 75 karakte
expectation = gx.expectations.ExpectColumnValueLengthsToBeBetween(
    column="Product",
    min_value=5,
    max_value=75
)
result = batch.validate(expectation)
result

Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]

{
  "success": true,
  "expectation_config": {
    "type": "expect_column_value_lengths_to_be_between",
    "kwargs": {
      "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
      "column": "Product",
      "min_value": 5,
      "max_value": 75
    },
    "meta": {},
    "severity": "critical"
  },
  "result": {
    "element_count": 112036,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0,
    "partial_unexpected_counts": [],
    "partial_unexpected_index_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [46]:
# Expectation 7 - Table Row Count To Be Between
## untuk memvalidasi jumlah row di tabel harus diantara 100000 dan 120000
expectation = gx.expectations.ExpectTableRowCountToBeBetween(
    min_value=100000,
    max_value=120000
)
result = batch.validate(expectation)
result

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "expectation_config": {
    "type": "expect_table_row_count_to_be_between",
    "kwargs": {
      "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
      "min_value": 100000,
      "max_value": 120000
    },
    "meta": {},
    "severity": "critical"
  },
  "result": {
    "observed_value": 112036
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

Kumpulkan semua Expectations ke Expectation Suite, agar nanti bisa dialankan dalam 1 Checkpoint

In [47]:
suite = context.suites.add(
    gx.ExpectationSuite(name="europe-bike-sales-suite")
)

suite.add_expectation(gx.expectations.ExpectColumnValuesToBeUnique(column="Transaction_ID"))
suite.add_expectation(gx.expectations.ExpectColumnValuesToBeBetween(column="Customer_Age", min_value=0, max_value=100))
suite.add_expectation(gx.expectations.ExpectColumnValuesToBeInSet(column="Customer_Gender", value_set=["M", "F"]))
suite.add_expectation(gx.expectations.ExpectColumnValuesToBeInTypeList(column="Date", type_list=["datetime64[ns]"]))
suite.add_expectation(gx.expectations.ExpectColumnPairValuesAToBeGreaterThanB(column_A="Unit_Price", column_B="Unit_Cost", or_equal=True))
suite.add_expectation(gx.expectations.ExpectColumnValueLengthsToBeBetween(column="Product", min_value=5, max_value=75))
suite.add_expectation(gx.expectations.ExpectTableRowCountToBeBetween(min_value=100000, max_value=120000))

ExpectTableRowCountToBeBetween(id='135b75a0-639a-4f33-9af5-f624a2c75487', meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=False, rendered_content=None, severity=<FailureSeverity.CRITICAL: 'critical'>, windows=None, batch_id=None, min_value=100000, max_value=120000, strict_min=False, strict_max=False, row_condition=None, condition_parser=None)

Hubungkan "batch_definition" dengan "suite", lalu gabung keduanya sebelum dijalankan lewat Checkpoint

In [48]:
validation_definition = context.validation_definitions.add(
    gx.ValidationDefinition(
        name="europe-bike-sales-validation",
        data=batch_definition,
        suite=suite,
    )
)

Bungkus Validation Definition diatas jadi satu kesatuan yaitu "Checkpoint", dan Jalankan Checkpointnya

In [49]:
checkpoint = context.checkpoints.add(
    gx.Checkpoint(
        name="bike-sales-checkpoint",
        validation_definitions=[validation_definition],
    )
)

In [50]:
checkpoint_result = checkpoint.run(batch_parameters={"dataframe": df})
checkpoint_result

Calculating Metrics:   0%|          | 0/41 [00:00<?, ?it/s]

CheckpointResult(run_id={"run_name": null, "run_time": "2026-09-16T20:40:01.292411+07:00"}, run_results={ValidationResultIdentifier::europe-bike-sales-suite/__none__/20260916T134001.292411Z/europe-bike-sales-source-europe-bike-sales-asset: {
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
          "column": "Transaction_ID"
        },
        "meta": {},
        "id": "ec4b5dcd-5172-4c2c-a5ea-75f39b85667f",
        "severity": "critical"
      },
      "result": {
        "element_count": 112036,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
          "column": "Customer_Age",
          "min_value": 0.0,
          "max_value": 100.0
        },
        "meta": {},
        "id": "c97033ba-1df1-4591-b7cb-ffb67fa41576",
        "severity": "critical"
      },
      "result": {
        "element_count": 112036,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_in_set",
        "kwargs": {
          "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
          "column": "Customer_Gender",
          "value_set": [
            "M",
            "F"
          ]
        },
        "meta": {},
        "id": "ede97061-872e-4145-b61b-255b76c3e7af",
        "severity": "critical"
      },
      "result": {
        "element_count": 112036,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_in_type_list",
        "kwargs": {
          "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
          "column": "Date",
          "type_list": [
            "datetime64[ns]"
          ]
        },
        "meta": {},
        "id": "ef526e01-99fc-4542-a444-689d4455a25c",
        "severity": "critical"
      },
      "result": {
        "observed_value": "datetime64"
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_pair_values_a_to_be_greater_than_b",
        "kwargs": {
          "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
          "column_A": "Unit_Price",
          "column_B": "Unit_Cost",
          "or_equal": true
        },
        "meta": {},
        "id": "73966fc4-a4df-4375-8a43-5f4aae302a7b",
        "severity": "critical"
      },
      "result": {
        "element_count": 112036,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_table_row_count_to_be_between",
        "kwargs": {
          "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
          "min_value": 100000,
          "max_value": 120000
        },
        "meta": {},
        "id": "135b75a0-639a-4f33-9af5-f624a2c75487",
        "severity": "critical"
      },
      "result": {
        "observed_value": 112036
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_value_lengths_to_be_between",
        "kwargs": {
          "batch_id": "europe-bike-sales-source-europe-bike-sales-asset",
          "column": "Product",
          "min_value": 5,
          "max_value": 75
        },
        "meta": {},
        "id": "46da70b9-f3ed-4f9e-a714-ae60c40cc74f",
        "severity": "critical"
      },
      "result": {
        "element_count": 112036,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "europe-bike-sales-suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 7,
    "successful_expectations": 7,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.23.0",
    "batch_spec": {
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20260916T134001.295842Z",
      "pandas_data_fingerprint": "947b2d62f05347b233c6e0a30994ec14"
    },
    "active_batch_definition": {
      "datasource_name": "europe-bike-sales-source",
      "data_connector_name": "fluent",
      "data_asset_name": "europe-bike-sales-asset",
      "batch_identifiers": {
        "dataframe": "<DATAFRAME>"
      }
    },
    "validation_id": "ecd252a9-7ee1-4d41-a800-a9e9d18510a3",
    "checkpoint_id": "2e06025a-ca9a-4135-ac5d-c03a8bb4eb6b",
    "run_id": {
      "run_name": null,
      "run_time": "2026-09-16T20:40:01.292411+07:00"
    },
    "validation_time": "2026-09-16T13:40:01.292411+00:00",
    "batch_parameters": {
      "dataframe": "<DATAFRAME>"
    }
  },
  "id": null
}}, checkpoint_config=Checkpoint(name='bike-sales-checkpoint', validation_definitions=[ValidationDefinition(name='europe-bike-sales-validation', data=BatchDefinition(id=UUID('1cd5272e-d187-47a5-bcfd-d3638ae14a74'), name='bike-sales-batch', partitioner=None), suite={
  "name": "europe-bike-sales-suite",
  "id": "1b147881-7b0c-4ec4-ae6a-b2a8e13575d6",
  "expectations": [
    {
      "type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "Transaction_ID"
      },
      "meta": {},
      "id": "ec4b5dcd-5172-4c2c-a5ea-75f39b85667f",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_between",
      "kwargs": {
        "column": "Customer_Age",
        "min_value": 0.0,
        "max_value": 100.0
      },
      "meta": {},
      "id": "c97033ba-1df1-4591-b7cb-ffb67fa41576",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "Customer_Gender",
        "value_set": [
          "M",
          "F"
        ]
      },
      "meta": {},
      "id": "ede97061-872e-4145-b61b-255b76c3e7af",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_in_type_list",
      "kwargs": {
        "column": "Date",
        "type_list": [
          "datetime64[ns]"
        ]
      },
      "meta": {},
      "id": "ef526e01-99fc-4542-a444-689d4455a25c",
      "severity": "critical"
    },
    {
      "type": "expect_column_pair_values_a_to_be_greater_than_b",
      "kwargs": {
        "column_A": "Unit_Price",
        "column_B": "Unit_Cost",
        "or_equal": true
      },
      "meta": {},
      "id": "73966fc4-a4df-4375-8a43-5f4aae302a7b",
      "severity": "critical"
    },
    {
      "type": "expect_column_value_lengths_to_be_between",
      "kwargs": {
        "column": "Product",
        "min_value": 5,
        "max_value": 75
      },
      "meta": {},
      "id": "46da70b9-f3ed-4f9e-a714-ae60c40cc74f",
      "severity": "critical"
    },
    {
      "type": "expect_table_row_count_to_be_between",
      "kwargs": {
        "min_value": 100000,
        "max_value": 120000
      },
      "meta": {},
      "id": "135b75a0-639a-4f33-9af5-f624a2c75487",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.0"
  },
  "notes": null
}, id='ecd252a9-7ee1-4d41-a800-a9e9d18510a3')], actions=[], result_format=<ResultFormat.SUMMARY: 'SUMMARY'>, id='2e06025a-ca9a-4135-ac5d-c03a8bb4eb6b'), success=True)

Ubah data hasil Validasi menggunakan Great Expectation yang semua sudah dijalankan menjadi sebuah Data Docs

In [51]:
# Versi Directory untuk menampilkan Data Docs
context.build_data_docs()

{'local_site': 'file://C:\\Users\\rolan\\AppData\\Local\\Temp\\tmp8dq3q6lx\\index.html'}

In [52]:
# Versi Browser untuk menampilkan Data Docs
context.open_data_docs()